# Generated by Django 2.2.7 on 2019-11-16 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guestPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.barcode')),
                ('date_valid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.date')),
                ('guest_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
