# Generated by Django 2.2.7 on 2019-11-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_auto_20191119_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
