# Generated by Django 2.2.7 on 2019-11-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=20, unique=True)),
                ('student_class', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/studentlists/')),
                ('migrated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
